[package]
name = "hphb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
once_cell = "1.17.1"
rand = "0.8.5"

[features]
default = ["random", "cli"]
random = []
cli = []
